language: python
python:
  - "3.7"
services:
  - "docker"

install:
  - "pip install -r requirements.txt"
script:
  - "pylint --load-plugins pylint_quotes packet/routes packet"
  - "docker build -t packet ."
