"""Change signature column names

Revision ID: 1812144b6cd6
Revises: 4170611e5cc0
Create Date: 2018-02-07 05:48:47.001644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1812144b6cd6'
down_revision = '4170611e5cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_fresh',
    sa.Column('packet', sa.Integer(), nullable=False),
    sa.Column('freshman', sa.Integer(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['freshman'], ['freshman.id'], ),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet')
    )
    op.create_table('signature_misc',
    sa.Column('packet', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet')
    )
    op.create_table('signature_upper',
    sa.Column('packet', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet')
    )
    op.drop_table('fresh_signature')
    op.drop_table('misc_signature')
    op.drop_table('upper_signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upper_signature',
    sa.Column('packet', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('signed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], name='upper_signature_packet_fkey'),
    sa.PrimaryKeyConstraint('packet', name='upper_signature_pkey')
    )
    op.create_table('misc_signature',
    sa.Column('packet', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], name='misc_signature_packet_fkey'),
    sa.PrimaryKeyConstraint('packet', name='misc_signature_pkey')
    )
    op.create_table('fresh_signature',
    sa.Column('packet', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('freshman', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('signed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['freshman'], ['freshman.id'], name='fresh_signature_freshman_fkey'),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], name='fresh_signature_packet_fkey'),
    sa.PrimaryKeyConstraint('packet', name='fresh_signature_pkey')
    )
    op.drop_table('signature_upper')
    op.drop_table('signature_misc')
    op.drop_table('signature_fresh')
    # ### end Alembic commands ###
