"""Updated DateTime for All Signatures

Revision ID: 1be1b2d119a8
Revises: 1812144b6cd6
Create Date: 2018-02-07 17:04:45.709858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be1b2d119a8'
down_revision = '1812144b6cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signature_fresh', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('signature_misc', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('signature_upper', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signature_upper', 'updated')
    op.drop_column('signature_misc', 'updated')
    op.drop_column('signature_fresh', 'updated')
    # ### end Alembic commands ###
