"""empty message

Revision ID: 3f9e2b235190
Revises: 1be1b2d119a8
Create Date: 2018-07-28 15:38:48.453770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9e2b235190'
down_revision = '1be1b2d119a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packet', 'announce')
    # ### end Alembic commands ###

    # Hand-written commands - won't be rolled back by downgrade
    op.drop_constraint('signature_upper_pkey', 'signature_upper', type_='primary')
    op.create_primary_key('signature_upper_pkey', 'signature_upper', ['packet', 'member'])

    op.drop_constraint('signature_fresh_pkey', 'signature_fresh', type_='primary')
    op.create_primary_key('signature_fresh_pkey', 'signature_fresh', ['packet', 'freshman'])

    op.drop_constraint('signature_misc_pkey', 'signature_misc', type_='primary')
    op.create_primary_key('signature_misc_pkey', 'signature_misc', ['packet', 'member'])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packet', sa.Column('announce', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
