"""Initial Database Schema

Revision ID: 4170611e5cc0
Revises:
Create Date: 2018-02-07 05:45:14.686327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4170611e5cc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freshman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('onfloor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freshman', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('announce', sa.Text(), nullable=True),
    sa.Column('info_eboard', sa.Text(), nullable=True),
    sa.Column('info_events', sa.Text(), nullable=True),
    sa.Column('info_achieve', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['freshman'], ['freshman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fresh_signature',
    sa.Column('packet', sa.Integer(), nullable=False),
    sa.Column('freshman', sa.Integer(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['freshman'], ['freshman.id'], ),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet')
    )
    op.create_table('misc_signature',
    sa.Column('packet', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet')
    )
    op.create_table('upper_signature',
    sa.Column('packet', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['packet'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upper_signature')
    op.drop_table('misc_signature')
    op.drop_table('fresh_signature')
    op.drop_table('packet')
    op.drop_table('freshman')
    # ### end Alembic commands ###
