"""Initial db schema

Revision ID: b1c013f236ab
Revises: 
Create Date: 2018-07-28 18:26:53.716828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c013f236ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freshman',
    sa.Column('rit_username', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('onfloor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('rit_username')
    )
    op.create_table('packet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freshman_username', sa.String(length=10), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('info_eboard', sa.Text(), nullable=True),
    sa.Column('info_events', sa.Text(), nullable=True),
    sa.Column('info_achieve', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['freshman_username'], ['freshman.rit_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_fresh',
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('freshman', sa.String(length=10), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freshman'], ['freshman.rit_username'], ),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet_id', 'freshman')
    )
    op.create_table('signature_misc',
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet_id', 'member')
    )
    op.create_table('signature_upper',
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('member', sa.String(length=36), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('eboard', sa.Boolean(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('packet_id', 'member')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signature_upper')
    op.drop_table('signature_misc')
    op.drop_table('signature_fresh')
    op.drop_table('packet')
    op.drop_table('freshman')
    # ### end Alembic commands ###
