"""Demote Eboard Deluxe

Revision ID: eecf30892d0e
Revises: fe83600ef3fa
Create Date: 2019-02-14 17:41:18.469840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecf30892d0e'
down_revision = 'fe83600ef3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signature_upper', sa.Column('active_rtp', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('signature_upper', sa.Column('c_m', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('signature_upper', sa.Column('drink_admin', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('signature_upper', sa.Column('three_da', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('signature_upper', sa.Column('webmaster', sa.Boolean(), nullable=False, server_default='f'))
    op.alter_column('signature_upper', 'eboard',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signature_upper', 'eboard',
               existing_type=sa.String(length=12),
               type_=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('signature_upper', 'webmaster')
    op.drop_column('signature_upper', 'three_da')
    op.drop_column('signature_upper', 'drink_admin')
    op.drop_column('signature_upper', 'c_m')
    op.drop_column('signature_upper', 'active_rtp')
    # ### end Alembic commands ###
