"""Remove essays

Revision ID: fe83600ef3fa
Revises: 0eeabc7d8f74
Create Date: 2018-10-22 21:55:15.257440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe83600ef3fa'
down_revision = '0eeabc7d8f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packet', 'info_events')
    op.drop_column('packet', 'info_eboard')
    op.drop_column('packet', 'info_achieve')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packet', sa.Column('info_achieve', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('packet', sa.Column('info_eboard', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('packet', sa.Column('info_events', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
